version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  redis:
    image: redis:latest

  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  worker:
    build: ./web
    command: celery -A your_project_name worker --loglevel=info
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - web

volumes:
  postgres_data: